### ISSUE TITLE
File list scrolls / jumps to top when opening viewer

### ISSUE THREAD

**Issue by pspitzli** [nextcloud/files_photospheres#90]
Steps to reproduce:
1. Enable Photosphere App in your nextcloud instance.
2. Create a folder with some JPGs and PNGs in it so your files view has to scroll
3. Scroll down to a JPG
4. Click on JPG

=> The View scrolls back up to the top thus loosing the previous scrolling position.
This is quite annoying when going through large folders.

See https://github.com/nextcloud/server/issues/33088 for further details. In Comment https://github.com/nextcloud/server/issues/33088#issuecomment-1205548024 the user @d-klx pointed me to the right solution for my problem: Disabling the Photosphere App.

This solves the scrolling issue.

**Comment by R0Wi** [comment]
Thank's for reporting this. Will try to reproduce it.

In the meantime: does this behaviour occur on every image or are just photosphere image affected?

**Comment by R0Wi** [comment]
Ok reproduced it. Happens on all kinds of images. Will try to figure out what's happening there.

**Comment by R0Wi** [comment]
@pspitzli i think i fixed it. Could you try it with the artifact from https://github.com/nextcloud/files_photospheres/suites/7772414911/artifacts/326956734 ?

**Comment by pspitzli** [comment]
> @pspitzli i think i fixed it. Could you try it with the artifact from https://github.com/nextcloud/files_photospheres/suites/7772414911/artifacts/326956734 ?

I will try it this evening.

**Comment by pspitzli** [comment]
The bug is still present.

How did I install the provided bundle:
1. `cd /var/www/nextcloud/apps`
2. `mv files_photospheres ~/files_photospheres.original`
3. `cp -r ~/files_photospheres ./`
4. `sudo systemctl restart php7.4-fpm`

I extracted your bundle into `~/files_photospheres` before doing that.
After that I reloaded my file view in the browser and checked if the bug was fixed.
Unfortunately the view is still being reloaded after a click on a JPG image.

**Comment by R0Wi** [comment]
Thank's for the feedback. Could you try to clear your browser caches? Could be that the old `.js`-files are still cached there.

**Comment by pspitzli** [comment]
Nope. Tried it in a fresh private window. Result is still the same. Sorry.

**Comment by R0Wi** [comment]
My mistake, i gave you a master branch build notthe one of my bugfix branch.

Could you try https://github.com/nextcloud/files_photospheres/suites/7798673424/artifacts/328861905 instead?

**Comment by pspitzli** [comment]
> Could you try https://github.com/nextcloud/files_photospheres/suites/7798673424/artifacts/328861905 instead?

Yes this build seems to fix the issue. The scroll position is not lost anymore.

**Comment by R0Wi** [comment]
Closed with `v1.24.1`, thanks @pspitzli for reporting this :rocket:
